# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Integration' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod "Descriptors", path: "../"
  pod "TextureSwiftSupport", path: "../Submodules/TextureSwiftSupport"
  pod "CompositionKit", path: "../Submodules/CompositionKit"
  # Pods for Integration

end
